#!/bin/bash
#
# Github Rezip
#
# Downloads and removes branch name from Github Zip files.
#
# Step 1: Save this bash script file to Desktop.
# Step 2: Open the terminal and navigate to Desktop.
# Step 3: Run the following: chmod 700 rezip.
# Step 4: Run the following: bash rezip owner/repo.
# Step 5: The Zip file will be saved to Desktop.

repo=$1
branch=master
base=`basename $repo`
url="https://github.com/${repo}/archive/${branch}.zip"

if [[ -n "$2" ]]; then
  branch=$2
fi

file="${branch}.zip"

if test -f "$file"; then
  echo "$file already exists. Please delete and try again."
  exit 1
fi

if test -f "${base}.zip"; then
  echo "${base}.zip already exists. Please delete and try again."
  exit 1
fi

if [[ -n "$repo" ]]; then
  wget -q $url
  unzip -qq $file
  mv "${base}-${branch}" $base
  wait
  zip -qr -r "${base}.zip" $base
  rm $file
  rm -r "${base}"

else
  echo "Please provide owner and repo information. E.g company/repo".
fi
